#######################
### HYPRLAND CONFIG ###
#######################

# --- 自動起動 ---
exec-once = waybar
# exec-once = hyprpaper
exec-once = swaybg -i /home/matcha/Downloads/2026_05_copy.jpeg -m fill
exec-once = fcitx5 -d


# --- 入力デバイスの設定 ---
input {
    kb_layout = jp
    follow_mouse = 1
    touchpad {
        natural_scroll = true
    }
}

# --- ウィンドウの見た目 ---
monitor=,preferred,auto,1.07
general {
    gaps_in = 3
    gaps_out = 5
    border_size = 3

    col.active_border = rgba(23,147,209,0.5)
    col.inactive_border = rgba(0,0,0,0)
}


dwindle {
    pseudotile = true
    preserve_split = true
}

$mainMod = SUPER
$terminal = ghostty

# --- 基本操作・アプリ起動 ---
bind = $mainMod, Q, exec, $terminal
bind = $mainMod, E, killactive
bind = $mainMod, M, exit
bind = $mainMod, R, exec, wofi --show drun
bind = $mainMod, J, togglesplit

# --- ウィンドウ間の移動 ---
bind = $mainMod, h,  movefocus, l
bind = $mainMod, l, movefocus, r
bind = $mainMod, k,    movefocus, u
bind = $mainMod, j,  movefocus, d

# --- ワークスペース切り替え ---
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5

# --- ウィンドウを別のワークスペースに移動 ---
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5

# --- マウス操作 ---
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# --- 日本語入力 (IME) の設定 ---
env = GTK_IM_MODULE, fcitx
env = QT_IM_MODULE, fcitx
env = XMODIFIERS, @im=fcitx
